//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWalk.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartWalk.Server.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access &apos;{0}&apos; select result items..
        /// </summary>
        internal static string CantAccessSelectResultItems {
            get {
                return ResourceManager.GetString("CantAccessSelectResultItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find &apos;{0}&apos; field in the requested items..
        /// </summary>
        internal static string CantFindFieldInRequestedItems {
            get {
                return ResourceManager.GetString("CantFindFieldInRequestedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find &apos;{0}&apos; table..
        /// </summary>
        internal static string CantFindTable {
            get {
                return ResourceManager.GetString("CantFindTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find &apos;{0}&apos; field in &apos;{1}&apos; select result items..
        /// </summary>
        internal static string CantFineFieldInSelectResultItems {
            get {
                return ResourceManager.GetString("CantFineFieldInSelectResultItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.From value can not be null..
        /// </summary>
        internal static string SelectFromCantBeNull {
            get {
                return ResourceManager.GetString("SelectFromCantBeNull", resourceCulture);
            }
        }
    }
}
